### ISSUE TITLE
Cheirality Failure on Lund

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsfm#472]
It seems that Lund door with SIFT frontend just crashes due to a Cheirality exception. Note I did use latest alpha release of GTSAM, but I don't think that should make a difference? Thoughs?

> command:

```bash
python gtsfm/runner/run_scene_optimizer_olssonloader.py --dataset_root tests/data/set1_lund_door --image_extension JPG --config_name sift_front_end.yaml --num_workers 1
```

> crash (which is remarkable uninformative as to *where* the error occurs):

```
libc++abi: terminating with uncaught exception of type gtsam::TriangulationCheiralityException: Triangulation Cheirality Exception: The resulting landmark is behind one or more cameras.
2022-05-05 15:01:26,722 - distributed.nanny - WARNING - Restarting worker
Traceback (most recent call last):
  File "gtsfm/runner/run_scene_optimizer_olssonloader.py", line 41, in <module>
    runner.run()
  File "/Users/dellaert/git/gtsfm/gtsfm/runner/gtsfm_runner_base.py", line 110, in run
    sfm_result = sfm_result_graph.compute()
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 3004, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2178, in gather
    return self.sync(
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 318, in sync
    return sync(
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 385, in sync
    raise exc.with_traceback(tb)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 358, in f
    result = yield future
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2041, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ('compute_correspondence_metrics-8de1a502-5bfe-4ddb-b952-f9f38805bb94', <WorkerState 'tcp://127.0.0.1:53704', name: 0, status: closed, memory: 0, processing: 265>)
2022-05-05 15:01:28,008 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x15b390670>>, <Task finished name='Task-13' coro=<Worker.close() done, defined at /Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py:757> exception=CommClosedError('ConnectionPool closing.')>)
Traceback (most recent call last):
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/core.py", line 1098, in _connect
    comm = await connect(
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/comm/core.py", line 313, in connect
    await asyncio.sleep(backoff)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/asyncio/tasks.py", line 659, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 759, in wrapper
    return await func(*args, **kwargs)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/worker.py", line 1519, in close
    await r.close_gracefully()
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/core.py", line 941, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/core.py", line 1162, in connect
    return await connect_attempt
  File "/Users/dellaert/mambaforge/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/core.py", line 1118, in _connect
    raise CommClosedError("ConnectionPool closing.")
distributed.comm.core.CommClosedError: ConnectionPool closing.
```

**Comment by dellaert** [comment]
Seems to be M1 specific. Fix is to compile locally, for now. I will also add triangulateSafe.
